### ISSUE TITLE
lastfmtube - WSError: Authentication Failed - You do not have permissions to access the service

### ISSUE THREAD

**Issue by Megachip** [Lunatixz/XBMC_Addons#3]
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                          
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                    
                                            Error Type: <class 'pylast.WSError'>                                                                                                
                                            Error Contents: Authentication Failed - You do not have permissions to access the service                                           
                                            Traceback (most recent call last):                                                                                                  
                                              File "/storage/.kodi/addons/plugin.audio.lastfmtube/default.py", line 350, in <module>                                            
                                                elif mode == 3: LastFMTube().getTopTracks(user, pwd)                                                                            
                                              File "/storage/.kodi/addons/plugin.audio.lastfmtube/default.py", line 250, in getTopTracks                                        
                                                network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET, username=user, password_hash=pwd)                        
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 934, in __init__                                   
                                                "user": "user/%(name)s",                                                                                                        
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 274, in __init__                                   
                                                self.username, self.password_hash)                                                                                              
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 1353, in get_session_key                           
                                                doc = request.execute()                                                                                                         
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 1233, in execute                                   
                                                response = self._download_response()                                                                                            
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 1224, in _download_response                        
                                                self._check_response_for_errors(response_text)                                                                                  
                                              File "/storage/.kodi/addons/script.module.pylast/lib/pylast/__init__.py", line 1253, in _check_response_for_errors                
                                                raise WSError(self.network, status, details)                                                                                    
                                            WSError: Authentication Failed - You do not have permissions to access the service                                                  
                                            -->End of Python script error report<--`

Username and PW are correct :(

**Comment by Lunatixz** [comment]
Your profile must be public, double check you are sharing your lastfm play history.

**Comment by Megachip** [comment]
@Lunatixz it is. But why setup needs username and password when it uses public profiles?

**Comment by Lunatixz** [comment]
Depends on the data you are trying to access, API uses both public and auth. data... If you still encounter issues I'll need a full debug log. Usually this is related to username and password, make sure it's entered correctly (cap sensitive).
